en:
  languageCode: en
  languageName: English
  title: rwv's Blog
  menu:
    main:
      - name: Archive
        url: archives
        weight: 5
      - name: Search
        url: search
        weight: 10
      - name: Tags
        url: tags
        weight: 15
      - name: Homepage
        url: https://rwv.dev
  params:
    description: "rwv's Blog, sharing my journey."
    homeInfoParams:
      Title: "rwv's Blog"
      Content: >
        ЁЯСЛ Welcome to rwv's Blog!
zh:
  languageCode: zh-CN
  languageName: ф╕нцЦЗ
  title: ч┤лшПЬхНЪхов
  menu:
    main:
      - name: х╜Тцбг
        url: archives
        weight: 5
      - name: цРЬч┤в
        url: search
        weight: 10
      - name: цаЗчн╛
        url: tags
        weight: 15
      - name: ф╕╗щб╡
        url: https://rwv.dev
  params:
    description: "ч┤лшПЬхНЪховя╝Мшо░х╜Х rwv чЪДчВ╣чВ╣ц╗┤ц╗┤"
    homeInfoParams:
      Title: "ч┤лшПЬхНЪхов"
      Content: >
        ЁЯСЛ цмвш┐ОцЭехИ░ч┤лшПЬхНЪховя╝Б
