displayFullLangName: true
author: "rwv"
ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowFullTextinRSS: true
ShowWordCount: true

editPost:
  URL: "https://github.com/rwv/blog/blob/main/content"
  appendFilePath: true # to append file path to Edit link
ShowCodeCopyButtons: true
